name: flutter_scroll_shadow_example
description: A demonstration of the ScrollShadow widget for a scrollable child.
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_scroll_shadow:
    path: ../

flutter:
  uses-material-design: true
