name: flutter_scroll_shadow
description: ScrollShadow adds shadows to a scrollable child. Supports ScrollController and vertical or horizontal orientation.
version: 0.1.0-alpha.2
repository: https://github.com/rickypid/flutter_scroll_shadow
issue_tracker: https://github.com/rickypid/flutter_scroll_shadow/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
